remote_theme: pages-themes/midnight@v0.2.0

plugins:
- jekyll-remote-theme

title: Capstone Project Site
description: Kirsch, McLaughlin, Linares, Patterson, Butler

url: https://gothiclolita229.github.io/capstonesite.github.io/

lang: en
last_updated: true

# Menu 

navigation:
  - {file: "index.html", title: Home}
  - {file: "README.md", title: About}
